### ISSUE TITLE
help building KCT

### ISSUE THREAD

**Issue by 7ranceaddic7** [magico13/KCT#145]
Trying to learn more about building mods directly.  I've learned how to add References and Packages, but when it comes to coding ... fugetaboutit. Using MonoDevelop.

Can anyone point me in the right direction to clear these build errors?

KCT_BuildListVessel.cs(160,68): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
KCT_Events.cs(553,43): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
KCT_Utilities.cs(1012,135): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level

Application Output
<
Building Solution: KerbalConstructionTime (Release)

Building: KerbalConstructionTime (Release)

Build started 11/3/2016 1:38:22 PM.
__________________________________________________
Project "/home/scott/Downloads/temp/KCT-1.3.4.1/Kerbal_Construction_Time/KerbalConstructionTime.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Release Platform: AnyCPU
	
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	
	Target CoreCompile:
		Tool /home/scott/Downloads/temp/KCT-1.3.4.1/packages/Microsoft.Net.Compilers.1.3.2/build/../tools/csc.exe execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/Release/KerbalConstructionTime.dll CrewQAPI.cs IKCTBuildItem.cs KACWrapper.cs KCTDebug.cs KCT_BuildListStorage.cs KCT_BuildListVessel.cs KCT_Events.cs KCT_GameStates.cs KCT_GUI.cs KCT_DataStorage.cs KCT_GUI_BuildList.cs KCT_GUI_Presets.cs KCT_KSC.cs KCT_LaunchPad.cs KCT_MathParsing.cs KCT_OrbitAdjuster.cs KCT_PresetManager.cs KCT_Recon_Rollout.cs KCT_Settings.cs KCT_TechControl.cs KCT_UpdateChecker.cs KCT_Utilities.cs KerbalConstructionTime.cs Properties/AssemblyInfo.cs StageRecoveryWrapper.cs ToolbarWrapper.cs Properties/VersionInfo.cs /target:library /define:TRACE /nostdlib /reference:../../../../Games/KSP_linux-1_2/KSP_Data/Managed/Assembly-CSharp.dll /reference:../../../../Games/KSP_linux-1_2/GameData/MagiCore/MagiCore.dll /reference:/usr/lib/mono/2.0-api/System.dll /reference:/usr/lib/mono/2.0-api/System.Data.dll /reference:/usr/lib/mono/2.0-api/System.Xml.dll /reference:../../../../Games/KSP_linux-1_2/KSP_Data/Managed/UnityEngine.dll /reference:../../../../Games/KSP_linux-1_2/KSP_Data/Managed/UnityEngine.UI.dll /reference:/usr/lib/mono/2.0-api/System.Core.dll /reference:/usr/lib/mono/2.0-api//mscorlib.dll /warn:4
		Microsoft (R) Visual C# Compiler version 1.3.1.60621
		Copyright (C) Microsoft Corporation. All rights reserved.
		
KCT_BuildListVessel.cs(160,68): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
KCT_Events.cs(553,43): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
KCT_Utilities.cs(1012,135): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
	Task "Csc" execution -- FAILED
	Done building target "CoreCompile" in project "/home/scott/Downloads/temp/KCT-1.3.4.1/Kerbal_Construction_Time/KerbalConstructionTime.csproj".-- FAILED
	
Done building project "/home/scott/Downloads/temp/KCT-1.3.4.1/Kerbal_Construction_Time/KerbalConstructionTime.csproj".-- FAILED

Build FAILED.
Errors:

/home/scott/Downloads/temp/KCT-1.3.4.1/Kerbal_Construction_Time/KerbalConstructionTime.csproj (Build) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	KCT_BuildListVessel.cs(160,68): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
	KCT_Events.cs(553,43): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level
	KCT_Utilities.cs(1012,135): error CS0122: 'ProtoPartResourceSnapshot.resourceValues' is inaccessible due to its protection level

	 0 Warning(s)
	 3 Error(s)

Time Elapsed 00:00:01.2721850

---------------------- Done ----------------------

Build: 3 errors, 0 warnings
>

**Comment by magico13** [comment]
If you're trying to build the Master branch against KSP v1.2 you're going to have a bad, bad time. Try the Development branch instead. The Master branch won't work in 1.2 even if you get it to build. Btw, there are already compiled versions of the dev branch at http://magico13.net/files/KSP/KCT_dev/ ([see this forum post as well](http://forum.kerbalspaceprogram.com/index.php?/topic/62900-kerbal-construction-timestagerecovery-dev-thread/))

If you still want to know how to clear those errors, it's a 1.2 upgrade specific problem. They made the resourceValues variable protected (or private, but I'm pretty sure it's protected or internal). There's a new method of accessing that data in 1.2 that's already taken care of in the dev branch. I don't remember the exact change off the top of my head, but there's a forum post about it in the Addon Dev forum I think.

**Comment by 7ranceaddic7** [comment]
Thank you.
